//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HRMS.rc
//
#define IDB_FILE_RECORD_RESET           3
#define ID_PRINT                        4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HRMS_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_MENU              129
#define IDD_FILE_RECORD                 130
#define IDD_FILESEARCH_DLG              134
#define IDD_DEPT_INFO                   135
#define IDD_DEPT_DUTY_INFO              136
#define IDR_ACCELERATOR1                137
#define IDD_EMPLOYEE_BARGAIN            138
#define IDD_LOAD_TEMPLATE               141
#define IDD_LOAD_IN_TEMPLATE            142
#define IDD_FIND_EMPLOYEE               143
#define IDI_ICON1                       151
#define IDI_ICON2                       152
#define IDI_ICON3                       153
#define IDI_ICON4                       154
#define IDI_ICON5                       155
#define IDB_BITMAP1                     156
#define IDD_TIMECARD                    157
#define IDD_ABSENCE                     158
#define IDD_PAYLIST                     160
#define IDD_PAYSLIP                     161
#define IDD_LANDING                     162
#define IDD_REGISTER_USER               163
#define IDD_CONFIG                      164
#define IDD_APPLY_EMPLOYEE              165
#define IDD_APPLERINFO                  167
#define IDD_OPERATION_ASSESS            169
#define IDD_APPLERLIST                  172
#define IDD_ASSESSLIST                  174
#define IDD_REQUESTLIST                 175
#define IDI_ICON6                       177
#define IDB_BITMAP2                     179
#define IDB_BITMAP3                     180
#define IDB_BITMAP4                     181
#define IDB_BITMAP5                     182
#define IDB_BITMAP6                     183
#define IDB_BITMAP7                     184
#define IDB_BITMAP8                     185
#define IDB_BITMAP9                     186
#define IDB_BITMAP10                    188
#define IDR_ITEM                        189
#define IDD_AGREEMENT_LIST              190
#define IDD_APPLER_SEARCH_DLG           191
#define IDD_SEARCH_REQUEST              193
#define IDD_ASSESS_SEARCH               195
#define IDD_PAYLIST_SEACH               197
#define IDD_LABORAGE_RECORD             199
#define IDD_LABORAGE_RECORD_SEARCH      200
#define IDD_LABORAGE_REC                202
#define IDR_PRINTMENU                   203
#define IDD_PRINTER                     204
#define IDD_HUMANREMOVE                 205
#define IDD_REQ_CHECK                   206
#define IDD_REQCHECKLIST                208
#define IDD_LEAVEITEM                   209
#define IDD_LEAVELIST                   211
#define IDR_DELITEM                     212
#define IDD_REQ_CHK_SEA                 213
#define IDD_FIND                        215
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_COMBO1                      1002
#define IDC_EDIT10                      1002
#define IDC_EDIT11                      1003
#define IDC_COMBO5                      1003
#define IDC_EDIT12                      1004
#define IDC_COMBO6                      1004
#define IDC_EDIT13                      1005
#define IDC_EDIT14                      1006
#define IDC_EDIT15                      1007
#define IDC_COMBO2                      1012
#define IDC_COMBO4                      1013
#define IDC_COMBO3                      1014
#define IDC_EDIT3                       1015
#define IDC_EDIT7                       1016
#define IDC_EDIT5                       1017
#define IDC_EDIT8                       1018
#define IDC_EDIT9                       1019
#define IDB_FILE_RECORD_SAVE            1020
#define IDC_LOADPICTURE                 1021
#define IDC_EDIT6                       1022
#define IDC_DATETIMEPICKER1             1024
#define IDC_LIST1                       1026
#define IDC_COMPACT_EDIT                1027
#define IDC_DATETIMEPICKER2             1028
#define ID_APPEND                       1029
#define IDC_DATETIMEPICKER3             1029
#define IDC_LIST2                       1030
#define IDC_ADD                         1031
#define IDC_EDIT4                       1032
#define IDC_DEL                         1033
#define IDC_DUTYLIST                    1034
#define IDC_EDGE                        1036
#define IDC_EDITDEPTINFO                1037
#define IDC_LOAD_BARGAIN_ITEM           1038
#define IDR_FILE_SEARCH_MENU            1038
#define IDC_BARGAIN_SAVE                1039
#define IDC_BARGAIN_RESET               1041
#define IDC_RADIO3                      1044
#define IDC_RADIO4                      1045
#define IDC_RADIO5                      1046
#define IDC_RADIO2                      1047
#define IDC_RADIO1                      1048
#define IDC_CHECK1                      1049
#define IDC_CHECK2                      1050
#define IDC_CHECK_USER_NAME             1051
#define IDC_EXPORT                      1061
#define IDC_EXPORTTOWORD                1062
#define IDC_PRINTMENUNU                 1063
#define IDC_EXPORTWORD                  1068
#define IDC_EXPORT_TO_WORD              1070
#define ID_EXPORT                       1071
#define IDC_SEELIST                     1072
#define IDC_ADDNEW                      1073
#define IDM_EXIT                        32771
#define IDM_FILE_RECORD                 32772
#define IDM_FILE_SEARCH                 32773
#define IDM_INSERTDEPT                  32774
#define IDM_DEPT_DUTY                   32775
#define ID_FIND_EMPLOYEE                -32759
#define IDM_LOAD_OUT                    32780
#define IDM_LOAD_IN                     32781
#define IDM_OPEN                        32782
#define ID_ABOUT                        32783
#define IDM_HELP                        32784
#define ID_ATTENDANCE_RECORD            32785
#define ID_USER_REGISTER                32787
#define IDM_MODI_CODE                   32788
#define IDM_TIMECARD_LIST               32789
#define IDM_PAY                         32790
#define IDM_PAYLIP                      32791
#define IDM_APPLERFILE                  32792
#define IDM_REQUEST_EMPLOYEE            32793
#define IDM_SETCONFIG                   32794
#define IDM_PORTFOLIO                   32795
#define IDM_PORTFOLIO_LIST              32796
#define IDM_EXPORT                      32797
#define IDM_APPLERLIST                  32798
#define IDM_RESETLAND                   32799
#define IDM_QUITLAND                    32800
#define IDM_REAUESTLIST                 32801
#define IDM_DELETEITEM                  32802
#define IDM_EDIT                        32803
#define IDM_QUIT                        32804
#define IDM_ABOUT                       32805
#define IDM_AGREEMENTEDIT               32806
#define IDM_AGREEMENTLIST               32808
#define IDM_LABORAGE                    32809
#define IDM_LABORAGE_LIST               32810
#define IDM_HUMAN_REDEPLOY              32811
#define IDM_EXAMINE_APPLICANT           32812
#define IDM_EXAMINE_LIST                32813
#define IDM_SEARCH_RECORD               32814
#define ID_LABORAGE_RECORD              32815
#define IDM_PRINTER                     32816
#define IDM_PREVIEW                     32817
#define IDM_LEAVEITEM                   32818
#define IDM_LEAVELIST                   32819
#define ID_DELITEM                      32820
#define IDM_FIND                        32821

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        217
#define _APS_NEXT_COMMAND_VALUE         32822
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
