//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by bbb.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BBB_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDR_TOOLBAR1                    130
#define IDB_BITMAP1                     132
#define IDB_BITMAP2                     133
#define IDI_ICON1                       134
#define IDI_ICON2                       135
#define IDI_ICON3                       136
#define IDI_ICON4                       137
#define IDI_ICON5                       138
#define IDI_ICON6                       139
#define IDI_ICON7                       140
#define IDI_ICON8                       141
#define IDI_ICON9                       142
#define IDI_ICON10                      143
#define IDB_BITMAP3                     145
#define IDB_BITMAP4                     146
#define IDB_BITMAP5                     148
#define IDB_BITMAP6                     149
#define IDB_BITMAP7                     150
#define IDC_WRITEMSG                    151
#define IDB_BITMAP8                     151
#define IDC_GETALLSIM                   152
#define IDB_BITMAP9                     152
#define IDC_MSG_BUTTONSPLI              153
#define IDB_BITMAP10                    153
#define IDC_SCHOOL_REPORT_CARD          154
#define IDC_TELBOOK                     155
#define IDC_MSG_RECIEVED                156
#define IDC_MSG_SENDED                  157
#define IDC_MSG_DELETED                 158
#define IDB_BITMAP24                    158
#define IDC_REFRESH                     159
#define IDB_BITMAP22                    159
#define IDB_BITMAP23                    160
#define IDB_BITMAP21                    161
#define IDB_BITMAP11                    162
#define IDD_BASE_INFO_M                 167
#define IDD_STORE_INFO_M                168
#define IDD_QUERY_M                     169
#define IDD_CONFIG                      170
#define IDD_OPERATOR                    171
#define IDD_OPERATOR1                   172
#define IDD_DESK_INOF                   173
#define IDD_DESK_INOF1                  174
#define IDD_BOOK_KINDS                  175
#define IDD_PROVIDER_INFO1              176
#define IDD_PROVIDER_INFO               177
#define IDD_BOOK_INFO1                  178
#define IDD_BOOK_INFO                   179
#define IDD_BOOK_KINDS1                 180
#define IDD_STORE_INFO                  181
#define IDD_STORE_INFO1                 182
#define IDD_BOOK_INPUT                  183
#define IDD_INPUT_BACK                  184
#define IDD_INPUT_BACK2                 185
#define IDD_BOOK_ADJUST                 186
#define IDD_BOOK_ADJUST2                187
#define IDD_BOOK_SALE                   188
#define IDD_BOOK_SALE2                  189
#define IDD_SALE_BACK                   190
#define IDD_SALE_QUERY3                 191
#define IDD_BOOK_INPUT2                 192
#define IDD_BOOK_PRICE                  193
#define IDD_BOOK_PRICE2                 194
#define IDD_BOOK_ADJUST_PRICE           195
#define IDD_BOOK_ADJUST_PRICE2          196
#define IDD_SALE_BACK2                  197
#define IDD_INPUT_QUERY                 198
#define IDD_INPUT_QUERY3                199
#define IDD_INPUT_BACK_QUERY            200
#define IDD_INPUT_BACK_QUERY3           201
#define IDD_SALE_QUERY                  202
#define IDD_SALE_BACK_QUERY             203
#define IDD_SALE_BACK_QUERY3            204
#define IDD_SYS_M                       205
#define IDD_DIALOG2                     206
#define IDI_ICON17                      217
#define IDI_ICON19                      218
#define IDI_ICON11                      219
#define IDI_ICON14                      220
#define IDI_ICON18                      221
#define IDI_ICON15                      222
#define IDI_ICON16                      223
#define IDI_ICON12                      224
#define IDI_ICON13                      225
#define IDD_LOGIN                       226
#define IDB_LOGIN                       228
#define IDB_BITMAP12                    243
#define IDC_ADD                         301
#define IDC_MODIFY                      302
#define IDC_QUERY                       303
#define IDC_DEL                         304
#define IDC_FIRST                       305
#define IDC_BEFORE                      306
#define IDC_AFTER                       307
#define IDC_END                         308
#define IDC_SHUTDOWN                    309
#define IDC_print                       310
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_BUTTON3                     1002
#define IDC_BUTTON4                     1003
#define IDC_EDIT1                       1004
#define IDC_OPERATOR                    1004
#define IDC_BOOK_NAME1                  1004
#define IDC_PROVIDER1                   1004
#define IDC_EDIT2                       1005
#define IDC_PASSWORD                    1005
#define IDC_BOOK_ZHJ_CODE1              1005
#define IDC_PROVIDER_CEO1               1005
#define IDC_BUTTON5                     1006
#define IDC_BOOK_TX_CODE1               1006
#define IDC_MANAGER1                    1006
#define IDC_SUMMONEY                    1006
#define IDC_BUTTON6                     1007
#define IDC_TAB1                        1007
#define IDC_BOOK_AUTHOR1                1007
#define IDC_PROVIDER_PHONE1             1007
#define IDC_REBATE                      1007
#define IDC_BUTTON7                     1008
#define IDC_BOOK_PUBLIC1                1008
#define IDC_PROVIDER_ADDRESS1           1008
#define IDC_PAYMONEY                    1008
#define IDC_BUTTON8                     1009
#define IDC_BOOK_PRICE1                 1009
#define IDC_NET_ADDRESS1                1009
#define IDC_FACTMONEY                   1009
#define IDC_COMB_JB                     1010
#define IDC_BOOK_MARK1                  1010
#define IDC_PROVIDER_EMAIL1             1010
#define IDC_BOOK_KINDS1                 1011
#define IDC_IPADDRESS1                  1011
#define IDC_EDIT3                       1012
#define IDC_EDIT4                       1013
#define IDC_BOOKNAME                    1013
#define IDC_EDIT5                       1014
#define IDC_AUTHOR                      1014
#define IDC_COMBO1                      1015
#define IDC_LIST1                       1016
#define IDC_COUNTER                     1016
#define IDC_STORAGELIST                 1017
#define IDC_NUM                         1017
#define IDC_BOOKREBATE                  1018
#define IDC_STATIC11                    1019
#define IDC_DATETIMEPICKER1             1020
#define IDC_DATETIMEPICKER2             1021
#define IDC_CHECK1                      1022
#define IDC_CHECK2                      1023
#define IDC_LIST2                       1024
#define IDC_PROVIDER                    1025
#define IDC_DATETIME                    1026
#define IDC_PROVIDERLIST                1027
#define IDC_FIELDS                      1029
#define IDC_VALUE                       1030
#define IDC_BARCODE                     1031
#define IDC_DETAILLIST                  1033
#define IDC_SELLPRICE                   1034
#define IDC_STORAGE                     1035
#define IDC_DATE                        1036
#define IDC_LIST                        1037
#define IDC_CUSTOMER                    1040
#define IDC_COUNTERNAME                 1041
#define IDC_CHANGE                      1042
#define IDC_CANCEL                      1043
#define IDC_EXIT                        1044
#define IDC_check                       1045
#define IDB_bookinfo                    5000
#define IDB_booksell                    5001
#define IDB_sellinfo                    5002
#define IDB_set                         5003
#define IDB_cancel                      5004
#define ID_EXIT                         32771
#define ID_FILE1                        32772
#define ID_BOOK_INPUT                   32772
#define ID_FILE2                        32773
#define ID_BOOK_PRICE                   32773
#define ID_BUTTON32774                  32774
#define ID_BUTTON32775                  32775
#define ID_ABUOUT                       32776
#define ID_OPERATOR_M                   32777
#define ID_BOOK_INFO                    32778
#define ID_PROVIDER_INFO                32779
#define ID_BOOK_TYPE                    32780
#define ID_CK_INFO                      32781
#define ID_DESK_INFO                    32782
#define ID_BOOK_PRICE_ADJUST            32783
#define ID_INPUT_BACK                   32784
#define ID_BOOK_ADJUST                  32785
#define ID_SALE_M                       32786
#define ID_SALE_BACK                    32787
#define ID_INPUT_QUERY                  32788
#define ID_INPUT_BACK_QUERY             32789
#define ID_SALE_QUERY                   32790
#define ID_SALE_BACK_QUERY              32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        244
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
