//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mystudentsys.rc
//
#define ID_BTNsave                      3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MYSTUDENTSYS_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     129
#define IDD_DIgofficeinfo               130
#define IDR_TOOLBAR_officeinfo          135
#define IDR_TOOLBAR_subjectinfo         136
#define IDD_DIg_subjectinfo             137
#define IDR_TOOLBAR_teacherinfo         137
#define IDD_DIgteacherinfo              138
#define IDR_TOOLBAR_classinfo           138
#define IDD_DIgclassinfo                139
#define IDR_TOOLBAR_classsubjectinfo    139
#define IDD_DIgclass_subject            140
#define IDR_TOOLBAR_examkinds           140
#define IDD_DIgexamkind                 141
#define IDR_MENU1                       142
#define IDD_DIgexaminfo_submark         143
#define IDD_DIgstudentinfo              144
#define IDD_DIgregbreak_input           145
#define IDD_DIgstudentreport            146
#define IDD_Dlgregbreak_find            147
#define IDB_BITMAP2                     149
#define IDD_DIggrade_leveldlg           151
#define IDD_LOGIN                       152
#define IDD_Dlguser                     153
#define IDI_ICON1                       154
#define IDB_BKBUTTON                    155
#define IDD_DIginfostudent              156
#define IDC_officeinfo                  1000
#define IDC_subjectinfo                 1001
#define IDC_EDIT_officename             1001
#define IDC_teacherinfo                 1002
#define IDC_BUTTON_pre                  1002
#define IDC_classinfo                   1003
#define IDC_BUTTON_next                 1003
#define IDC_subjectname                 1003
#define IDC_classsubject                1004
#define IDC_BUTTON_last                 1004
#define IDC_subjectid                   1004
#define IDC_teachername                 1004
#define IDC_examkind                    1005
#define IDC_BUTTON_first                1005
#define IDC_teacherid                   1005
#define IDC_BUTTON_add                  1006
#define IDC_teacherkonwledge            1006
#define IDC_BUTTON_del                  1007
#define IDC_COMBO_teachersex            1007
#define IDC_teacheroffice               1008
#define IDC_EDIT_classname              1008
#define IDC_teacherlevel                1009
#define IDC_EDIT_classteacher           1009
#define IDC_EDITclassname               1009
#define IDC_BUTTON_save                 1010
#define IDC_EDITclassid                 1010
#define IDC_EDIT_examkind               1010
#define IDC_sutentid                    1012
#define IDC_examsubject                 1013
#define IDC_submarks                    1014
#define IDC_inputsave_marks             1017
#define IDC_examdate_picker             1018
#define IDC_findstudent_id              1019
#define IDC_studentsex                  1020
#define IDC_studentage                  1021
#define IDC_studentphone                1022
#define IDC_studentname                 1023
#define IDC_studentclass                1024
#define IDC_studentaddr                 1025
#define IDC_findstudentinfo             1027
#define IDC_LIST1                       1029
#define IDC_regbreakstudentid           1030
#define IDC_regbreak_content            1031
#define IDC_regbreak_result             1032
#define IDC_regbreak_memo               1033
#define IDC_regbreak_date               1034
#define IDC_Btn_inputregbreak           1035
#define IDC_Btnreport                   1036
#define IDC_Btnreport_sorted            1037
#define IDC_EDIT_studentid              1037
#define IDC_Btnfind_regbreakinfo        1038
#define IDC_regfind_date                1039
#define IDC_EDIT_regcontent             1040
#define IDC_EDIT_reghandleresult        1041
#define IDC_EDIT_regmemo                1042
#define IDC_LIST2                       1044
#define IDC_EDIT_upgrade                1045
#define IDC_Btn_setgradelevel           1046
#define IDC_EDIT_lowgrade               1048
#define IDC_Btn_findbest                1056
#define IDC_Btnfindbetter               1057
#define IDC_Btnfindnormal               1058
#define IDC_Btnfindworse                1059
#define IDC_LIST3                       1060
#define IDC_COMBO1                      1061
#define IDC_TREE1                       1064
#define IDC_EDIT1                       1065
#define IDC_EDIT2                       1066
#define IDC_BUTTADD                     1067
#define IDC_BUTMOD                      1068
#define IDC_BUTDEL                      1069
#define ID_toolbar_add                  32780
#define ID_toolbar_save                 32781
#define ID_toolbar_del                  32782
#define ID_toolbar_first                32788
#define ID_toolbar_pre                  32789
#define ID_toolbar_next                 32790
#define ID_toolbar_last                 32792
#define ID_subjectinfo_toolbar_add      32793
#define ID_subjectinfo_toolbar_save     32794
#define ID_subjectinfo_toolbar_del      32795
#define ID_subjectinfo_toolbar_first    32796
#define ID_subjectinfo_toolbar_pre      32797
#define ID_subjectinfo_toolbar_next     32798
#define ID_subjectinfo_toolbar_last     32799
#define ID_teacherinfo_toolbar_add      32800
#define ID_teacherinfo_toolbar_save     32801
#define ID_teacherinfo_toolbar_del      32802
#define ID_teacherinfo_toolbar_first    32803
#define ID_teacherinfo_toolbar_pre      32804
#define ID_teacherinfo_toolbar_next     32805
#define ID_teacherinfo_toolbar_last     32806
#define ID_classinfo_toolbar_add        32807
#define ID_classinfo_toolbar_save       32808
#define ID_classinfo_toolbar_del        32809
#define ID_classinfo_toolbar_first      32810
#define ID_classinfo_toolbar_pre        32811
#define ID_classinfo_toolbar_next       32812
#define ID_classinfo_toolbar_last       32813
#define ID_classsubjectinfo_toolbar_add 32814
#define ID_classsubjectinfo_toolbar_save 32815
#define ID_classsubjectinfo_toolbar_del 32816
#define ID_classsubjectinfo_toolbar_first 32817
#define ID_classsubjectinfo_toolbar_pre 32818
#define ID_classsubjectinfo_toolbar_next 32819
#define ID_classsubjectinfo_toolbar_last 32820
#define ID_toolbar_examkind_add         32821
#define ID_toolbar_examkind_save        32822
#define ID_toolbar_examkind_del         32823
#define ID_toolbar_examkind_first       32824
#define ID_toolbar_examkind_pre         32825
#define ID_toolbar_examkind_next        32826
#define ID_toolbar_examkind_last        32827
#define ID_MENU_inputmarks              32828
#define ID_MENU_regbreakinfo            32829
#define ID_MENU_studentinfo             32830
#define ID_MENU_markreport              32831
#define ID_MENU_findbreakinfo           32833
#define ID_MENU_help                    32834
#define ID_ABOUT                        32835
#define ID_MENU_gradeleveldlg           32836
#define ID_MENU_user                    32837
#define ID_MENU_exit                    32838
#define ID_MENU_infostudent             32839
#define ID_MENU_officeinfo              32840
#define ID_MENU_subjectinfo             32841
#define ID_MENU_classinfo               32842
#define ID_MENU_teacherinfo             32843
#define ID_MENU_classsubject            32844
#define ID_MENU_examkind                32845

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32846
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
